# Generated by Django 6.1.1 on 2026-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='availability',
            field=models.CharField(choices=[('WEEKDAYS', 'Weekdays'), ('WEEKENDS', 'Weekends'), ('ANY', 'Any')], default='ANY', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='learning_preference',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In-Person'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
